### ISSUE TITLE
New medicines can't be added

### ISSUE THREAD

**Issue by danielwahlberg** [danielwahlberg/assistance-logger#3]
When trying to add a new medicine, The following is shown in server side log

```
exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/assistanceLog/api/v1/medicineService.php:189
Stack trace:
#0 /var/www/assistanceLog/api/v1/medicineService.php(189): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/var/www/assist...', 189, Array)
#1 /var/www/assistanceLog/api/v1/routes.php(86): MedicineService->storeDoseChange('[]')
#2 [internal function]: {closure}()
#3 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Middleware/ContentTypes.php(81): Slim\Middleware\MethodOverride->call()
#8 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\ContentTypes->call()
#9 /var/www/assistanceLog/assets/Slim-2.6.2/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#10 /var/www/assistanceLog/api/v1/api.php(32): Slim\Slim->run()
#11 {main}
```

**Comment by danielwahlberg** [comment]
Fixed in 4c9fb00886595ad24899794571852c52188d4908
